name: signal
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - anyio=3.6.1=pyhd8ed1ab_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310he2412df_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py310he2412df_1004
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py310haa95532_0
  - cffi=1.15.1=py310hcbf9ad4_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - contourpy=1.0.5=py310h232114e_0
  - cryptography=37.0.4=py310ha857299_0
  - curl=7.84.0=h2bbff1b_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py310h8a704f9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.2.0=h63175ca_1
  - eigen=3.4.0=h2d74725_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.0.0=pyhd8ed1ab_0
  - expat=2.5.0=h1537add_0
  - ffmpeg=4.3.1=ha925a31_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.37.2=py310h8d17308_0
  - freetype=2.12.1=h546665d_0
  - gettext=0.19.8.1=ha2e2712_1008
  - gl2ps=1.4.2=h0597ee9_0
  - glew=2.1.0=h39d44d4_2
  - glib=2.72.1=h7755175_0
  - glib-tools=2.72.1=h7755175_0
  - gst-plugins-base=1.20.3=h001b923_1
  - gstreamer=1.20.3=h6b5321d_1
  - hdf4=4.2.15=h0e5069d_4
  - hdf5=1.12.1=nompi_h2a0e4a3_104
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=70.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - imageio=2.22.0=pyhfa7a67d_0
  - importlib-metadata=4.11.4=py310h5588dad_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.15.3=pyh025b116_0
  - ipympl=0.9.2=pyhd8ed1ab_0
  - ipython=8.5.0=pyh08f2357_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h8ffe710_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsoncpp=1.9.5=h2d74725_1
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310h5588dad_0
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyterlab=3.4.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h476a331_0
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=4.0.0=h63175ca_0
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libclang=14.0.6=default_h77d9078_0
  - libclang13=14.0.6=default_h77d9078_0
  - libcurl=7.84.0=h86230a5_0
  - libdeflate=1.14=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.72.1=h3be07f2_0
  - libiconv=1.16=he774522_0
  - libnetcdf=4.8.1=nompi_h1cc8e9d_102
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.38=h19919ed_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.39.3=hcfcfb64_0
  - libssh2=1.10.0=h680486a_3
  - libtheora=1.1.1=h8d14728_1005
  - libtiff=4.4.0=h8e97e67_4
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.9.14=hf5bbc77_4
  - libxslt=1.1.35=h34f844d_0
  - libzip=1.9.2=hfed4ece_1
  - libzlib=1.2.12=hcfcfb64_3
  - llvmlite=0.38.0=py310h23ce68f_0
  - loguru=0.6.0=py310h5588dad_2
  - lxml=4.9.1=py310he2412df_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py310he2412df_1
  - matplotlib=3.5.2=py310haa95532_0
  - matplotlib-base=3.5.2=py310hd77b12b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.5.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nodejs=16.13.1=haa95532_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numba=0.55.1=py310h4ed8f06_0
  - numexpr=2.8.3=py310hb57aa6b_0
  - numpy=1.21.5=py310h6d2d95c_3
  - numpy-base=1.21.5=py310h206c741_3
  - openjpeg=2.5.0=hc9384bd_1
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.4=py310hd77b12b_0
  - pandoc=2.19.2=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310h52929f7_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - ply=3.11=py_1
  - proj=9.0.1=h1cfcee9_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pugixml=1.11.4=h0e60522_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyee=8.1.0=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyppeteer=1.0.2=pyhd8ed1ab_0
  - pyqt=5.15.7=py310hbabf5d4_0
  - pyqt5-sip=12.11.0=py310h8a704f9_0
  - pyrsistent=0.18.1=py310he2412df_1
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.6=h9a09f29_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyvista=0.36.1=pyhd8ed1ab_0
  - pyvistaqt=0.9.0=pyhd8ed1ab_0
  - pywin32=303=py310he2412df_0
  - pywinpty=2.0.7=py310h00ffb61_0
  - pyzmq=24.0.0=py310hcd737a0_0
  - qt-main=5.15.6=hf0cf448_0
  - qtpy=2.2.1=pyhd8ed1ab_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scikit-learn=1.0.2=py310h4ed8f06_0
  - scipy=1.7.3=py310h6d2d95c_0
  - scooby=0.7.0=pyhd8ed1ab_0
  - seaborn=0.12.2=py310haa95532_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - sip=6.6.2=py310h8a704f9_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.3=h2bbff1b_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - tbb=2021.6.0=h91493d7_1
  - tbb-devel=2021.6.0=h91493d7_1
  - terminado=0.15.0=py310h5588dad_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py310he2412df_0
  - tqdm=4.64.0=py310haa95532_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022c=h191b570_0
  - ucrt=10.0.20348.0=h57928b3_0
  - unicodedata2=14.0.0=py310he2412df_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - utfcpp=3.2.1=h57928b3_0
  - vc=14.2=hb210afc_7
  - vs2015_runtime=14.29.30139=h890b9b1_7
  - vtk=9.1.0=qt_py310h68bede9_210
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - websockets=10.3=py310he2412df_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - win32_setctime=1.1.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py310h5588dad_4
  - winpty=0.4.3=4
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h8cc25b3_3
  - zstd=1.5.2=h7755175_4
  - pip:
    - caerus==0.1.8
    - findpeaks==2.4.4
    - future==0.18.2
    - h5io==0.1.7
    - h5py==3.7.0
    - hampel==0.0.5
    - mne==1.2.0
    - peakdetect==1.1
    - pooch==1.6.0
    - pymatreader==0.0.30
    - wget==3.2
    - xmltodict==0.13.0
prefix: C:\Users\yyao\Anaconda3\envs\signal
